package mycompany.invoice;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.TextField;
import javafx.stage.Stage;

import java.net.URL;
import java.util.ResourceBundle;

import DAO.BuyerDAO;
import entity.Buyer;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.event.ActionEvent;

import javafx.scene.control.ComboBox;

public class AddBuyerController implements Initializable{
	
	private ObservableList<String> types =
	        FXCollections.observableArrayList(); 
	
	@FXML
	private TextField tfName;
	@FXML
	private TextField tfNip;
	@FXML
	private TextField tfCity;
	@FXML
	private TextField tfStreet;
	@FXML
	private TextField tfCode;
	@FXML
	private TextField tfState;
	@FXML
	private TextField tfNrTel;
	@FXML
	private TextField tfEmail;
	@FXML
	private ComboBox cbType;
	
	private boolean isNew = true;
	
	public void initData(Buyer b)
	{
		if(b == null) isNew = true;
		else {
		isNew = false;
		tfName.setText(b.getName());
		tfNip.setText(b.getId());
		tfCity.setText(b.getCity());
		tfStreet.setText(b.getStreet());
		tfCode.setText(b.getPostCode());
		tfState.setText(b.getState());
		tfNrTel.setText(b.getNr_tel());
		tfEmail.setText(b.getEmail());
		}
		if(!isNew)
		{
			tfNip.setEditable(false);
			cbType.setEditable(false);
		}
	}

	// Event Listener on Button.onAction
	@FXML
	public void addBuyer(ActionEvent event) {
		// TODO Autogenerated
		if(isNew)
		{
			Buyer b  = new Buyer();
			b.setName(tfName.getText());
			b.setId(tfNip.getText());
			b.setCity(tfCity.getText());
			b.setState(tfState.getText());
			b.setStreet(tfStreet.getText());
			b.setPostCode(tfCode.getText());
			b.setNr_tel(tfNrTel.getText());
			b.setEmail(tfEmail.getText());
			if(cbType.getValue().toString().equals("Firma"))
				b.setType("NIP");
			else if(cbType.getValue().toString().equals("Osoba Prywatna"))
				b.setType("PESEL");
		
			BuyerDAO.getInstance().addBuyer(b);
		}
		else
		{
			BuyerDAO.getInstance().update(tfNip.getText(),tfName.getText(),
					tfCity.getText(),tfState.getText(),tfStreet.getText(),
					tfCode.getText(),tfNrTel.getText(),tfEmail.getText());
		}
		
		Stage stage = (Stage) tfNip.getScene().getWindow();
		stage.close();
	}

	@Override
	public void initialize(URL location, ResourceBundle resources) {
		// TODO Auto-generated method stub
		types.add("Firma");
		types.add("Osoba Prywatna");
		cbType.setItems(types);
	}
	
	
}
