package mycompany.invoice;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Scene;
import javafx.scene.control.Alert;
import javafx.scene.control.Button;
import javafx.scene.control.ButtonType;
import javafx.scene.control.TextField;
import javafx.scene.control.Alert.AlertType;
import javafx.scene.layout.AnchorPane;
import javafx.scene.layout.BorderPane;
import javafx.stage.Stage;

import java.io.IOException;

import DAO.BuyerDAO;
import DAO.InvoiceDAO;
import DAO.JpaInitializer;
import DAO.PositionDAO;
import DAO.UserDAO;
import entity.User;
import javafx.event.ActionEvent;

import javafx.scene.control.PasswordField;

public class LogController {
	@FXML
	private TextField tfName;
	@FXML
	private PasswordField tfPass;
	@FXML
	private Button btnLog;
	@FXML
	private AnchorPane an;

	// Event Listener on Button[#btnLog].onAction
	@FXML
	public void log(ActionEvent event) throws IOException {
		// TODO Autogenerated
		String login = tfName.getText();
		String password = tfPass.getText();
		try {
		User user = UserDAO.getInstance().getUserByLogin(login, password);
		//TODO obsługa błędu jeśli user jest nullem
		JpaInitializer.getInstance().setCompatibilityLevel(user.getType());
		BuyerDAO.getInstance().setEm(JpaInitializer.getInstance().getEm());
		InvoiceDAO.getInstance().setEm(JpaInitializer.getInstance().getEm());
		PositionDAO.getInstance().setEm(JpaInitializer.getInstance().getEm());
		UserDAO.getInstance().setEm(JpaInitializer.getInstance().getEm());
		runIndexView(user);
		}
		catch(java.lang.IndexOutOfBoundsException e)
		{
			Alert alert = new Alert(AlertType.ERROR, "Błędny login lub hasło", ButtonType.CANCEL);
			alert.showAndWait();
		}
	}
	
	public void runIndexView(User user) throws IOException
	{
		FXMLLoader loader = new FXMLLoader();
		loader.setLocation(this.getClass().getResource("indexView.fxml"));

		BorderPane box = loader.load(); 
		MainViewController mvc = loader.<MainViewController>getController();
		mvc.setUser(user);

		Scene scene = new Scene(box);
		Stage primarystage = new Stage();
		primarystage.setScene(scene);
		primarystage.setTitle("Faktury");
		primarystage.setMaximized(true);
		primarystage.show();
		
		Stage stage = (Stage) an.getScene().getWindow();
		stage.close();
	}
}
